#!/bin/sh
here=$(pwd)
cd src
export LUA_PATH="./?.lua;./?/?.lua;./lib/?.lua;./lib/?/?.lua;$LUA_PATH"
lua grym.lua "$here" "$@"

cd ..

for d in orb/dot/samples/*.*.dot; do
    dot -Tsvg $d -o"$d".svg
    # echo "$d"
done

cd "$here"

