#!/bin/sh
here=$(pwd)

# replace the below with your directory of choice
cd ~/code/grym/src/ 

export LUA_PATH="./?.lua;./?/?.lua;./lib/?.lua;./lib/?/?.lua;$LUA_PATH"
lua grym.lua "$here" "$@"

cd "$here"
